name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5:i386 libstdc++6:i386 \
          libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 \
          unzip automake autoconf libtool pkg-config libssl-dev textinfo libgmp-dev \
          libmpfr-dev libmpc-dev swig libffi-dev openjdk-17-jdk zip apktool \
          libsqlite3-dev

    - name: Install Python Tools
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0"
        pip install buildozer kivy

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | buildozer android pdm || true

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: christianx-apk-debug
        path: bin/*.apk
